apiVersion: v1
kind: ServiceAccount
metadata:
  name: nrdot-collector
  namespace: nrdot-system
  labels:
    app.kubernetes.io/name: nrdot
    app.kubernetes.io/component: collector
    app.kubernetes.io/part-of: nrdot-host
automountServiceAccountToken: true
imagePullSecrets:
  - name: nrdot-registry-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nrdot-supervisor
  namespace: nrdot-system
  labels:
    app.kubernetes.io/name: nrdot
    app.kubernetes.io/component: supervisor
    app.kubernetes.io/part-of: nrdot-host
automountServiceAccountToken: true
imagePullSecrets:
  - name: nrdot-registry-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nrdot-config-engine
  namespace: nrdot-system
  labels:
    app.kubernetes.io/name: nrdot
    app.kubernetes.io/component: config-engine
    app.kubernetes.io/part-of: nrdot-host
automountServiceAccountToken: true
imagePullSecrets:
  - name: nrdot-registry-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nrdot-api-server
  namespace: nrdot-system
  labels:
    app.kubernetes.io/name: nrdot
    app.kubernetes.io/component: api-server
    app.kubernetes.io/part-of: nrdot-host
automountServiceAccountToken: true
imagePullSecrets:
  - name: nrdot-registry-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nrdot-privileged-helper
  namespace: nrdot-system
  labels:
    app.kubernetes.io/name: nrdot
    app.kubernetes.io/component: privileged-helper
    app.kubernetes.io/part-of: nrdot-host
automountServiceAccountToken: true
imagePullSecrets:
  - name: nrdot-registry-creds