# Prometheus configuration for NRDOT development

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'docker-dev'
    cluster: 'nrdot-local'

scrape_configs:
  # NRDOT Collector metrics
  - job_name: 'nrdot-collector'
    static_configs:
      - targets: ['collector:8888']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'nrdot-collector'

  # NRDOT API Server metrics
  - job_name: 'nrdot-api-server'
    static_configs:
      - targets: ['api-server:8080']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'nrdot-api-server'

  # NRDOT Supervisor metrics
  - job_name: 'nrdot-supervisor'
    static_configs:
      - targets: ['supervisor:8888']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'nrdot-supervisor'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Docker containers
  - job_name: 'docker-containers'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/?(.*)'
        target_label: container_name
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: project

# Alerting rules
rule_files:
  - /etc/prometheus/rules/*.yml

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []  # Add alertmanager targets if needed