version: '3.8'

services:
  # High cardinality metric generator
  metric-generator:
    build: ./metric-generator
    container_name: metric-generator
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://nrdot:4317
      - METRIC_COUNT=10000
      - CARDINALITY_LEVEL=high
    depends_on:
      - nrdot
    networks:
      - cardinality-network

  # NRDOT with cardinality limiting
  nrdot:
    image: nrdot-host:latest
    container_name: nrdot-cardinality
    volumes:
      - ./configs/nrdot-config.yaml:/etc/nrdot/config.yaml:ro
    environment:
      - NRDOT_CONFIG=/etc/nrdot/config.yaml
      - GOGC=25  # Aggressive garbage collection
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8888:8888"   # Metrics
      - "13133:13133" # Health check
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - cardinality-network

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-cardinality
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--log.level=debug'
    networks:
      - cardinality-network

  # VictoriaMetrics for comparison (handles high cardinality better)
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoria-metrics
    ports:
      - "8428:8428"
    command:
      - '-storageDataPath=/storage'
      - '-retentionPeriod=1h'
      - '-search.maxUniqueTimeseries=1000000'
    networks:
      - cardinality-network

networks:
  cardinality-network:
    driver: bridge