apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: api-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: data-collector-pdb
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: data-collector
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: data-processor-pdb
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: data-processor