{{- if .Values.serviceAccount.create -}}
{{- if .Values.collector.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nrdot.serviceAccountName" (dict "Context" . "component" "collector") }}
  namespace: {{ include "nrdot.namespace" . }}
  labels:
    {{- include "nrdot.componentLabels" (dict "Context" . "component" "collector") | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- if .Values.supervisor.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nrdot.serviceAccountName" (dict "Context" . "component" "supervisor") }}
  namespace: {{ include "nrdot.namespace" . }}
  labels:
    {{- include "nrdot.componentLabels" (dict "Context" . "component" "supervisor") | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- if .Values.configEngine.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nrdot.serviceAccountName" (dict "Context" . "component" "config-engine") }}
  namespace: {{ include "nrdot.namespace" . }}
  labels:
    {{- include "nrdot.componentLabels" (dict "Context" . "component" "config-engine") | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- if .Values.apiServer.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nrdot.serviceAccountName" (dict "Context" . "component" "api-server") }}
  namespace: {{ include "nrdot.namespace" . }}
  labels:
    {{- include "nrdot.componentLabels" (dict "Context" . "component" "api-server") | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- if .Values.privilegedHelper.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nrdot.serviceAccountName" (dict "Context" . "component" "privileged-helper") }}
  namespace: {{ include "nrdot.namespace" . }}
  labels:
    {{- include "nrdot.componentLabels" (dict "Context" . "component" "privileged-helper") | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}