{{- if .Values.collector.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nrdot.fullname" . }}-collector
  namespace: {{ include "nrdot.namespace" . }}
  labels:
    {{- include "nrdot.componentLabels" (dict "Context" . "component" "collector") | nindent 4 }}
  {{- with .Values.collector.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.collector.service.type }}
  selector:
    {{- include "nrdot.componentSelectorLabels" (dict "Context" . "component" "collector") | nindent 4 }}
  ports:
  - name: otlp-grpc
    port: {{ .Values.collector.service.ports.otlpGrpc.port }}
    targetPort: otlp-grpc
    protocol: TCP
  - name: otlp-http
    port: {{ .Values.collector.service.ports.otlpHttp.port }}
    targetPort: otlp-http
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nrdot.fullname" . }}-collector-internal
  namespace: {{ include "nrdot.namespace" . }}
  labels:
    {{- include "nrdot.componentLabels" (dict "Context" . "component" "collector") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "nrdot.componentSelectorLabels" (dict "Context" . "component" "collector") | nindent 4 }}
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: otlp-grpc
    protocol: TCP
  - name: otlp-http
    port: 4318
    targetPort: otlp-http
    protocol: TCP
  - name: metrics
    port: 8888
    targetPort: metrics
    protocol: TCP
  - name: health
    port: 13133
    targetPort: health
    protocol: TCP
  - name: zpages
    port: 55679
    targetPort: zpages
    protocol: TCP
{{- end }}
{{- if .Values.apiServer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nrdot.fullname" . }}-api
  namespace: {{ include "nrdot.namespace" . }}
  labels:
    {{- include "nrdot.componentLabels" (dict "Context" . "component" "api-server") | nindent 4 }}
  {{- with .Values.apiServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.apiServer.service.type }}
  selector:
    {{- include "nrdot.componentSelectorLabels" (dict "Context" . "component" "api-server") | nindent 4 }}
  ports:
  - name: https
    port: {{ .Values.apiServer.service.port }}
    targetPort: http
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nrdot.fullname" . }}-api-internal
  namespace: {{ include "nrdot.namespace" . }}
  labels:
    {{- include "nrdot.componentLabels" (dict "Context" . "component" "api-server") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "nrdot.componentSelectorLabels" (dict "Context" . "component" "api-server") | nindent 4 }}
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 8082
    targetPort: metrics
    protocol: TCP
{{- end }}
{{- if .Values.configEngine.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nrdot.fullname" . }}-config-engine
  namespace: {{ include "nrdot.namespace" . }}
  labels:
    {{- include "nrdot.componentLabels" (dict "Context" . "component" "config-engine") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "nrdot.componentSelectorLabels" (dict "Context" . "component" "config-engine") | nindent 4 }}
  ports:
  - name: health
    port: 8081
    targetPort: health
    protocol: TCP
  - name: metrics
    port: 8082
    targetPort: metrics
    protocol: TCP
{{- end }}
{{- if .Values.supervisor.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nrdot.fullname" . }}-supervisor
  namespace: {{ include "nrdot.namespace" . }}
  labels:
    {{- include "nrdot.componentLabels" (dict "Context" . "component" "supervisor") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "nrdot.componentSelectorLabels" (dict "Context" . "component" "supervisor") | nindent 4 }}
  ports:
  - name: health
    port: 8081
    targetPort: health
    protocol: TCP
  - name: metrics
    port: 8082
    targetPort: metrics
    protocol: TCP
  - name: api
    port: 8083
    targetPort: api
    protocol: TCP
{{- end }}
{{- if .Values.privilegedHelper.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nrdot.fullname" . }}-privileged-helper
  namespace: {{ include "nrdot.namespace" . }}
  labels:
    {{- include "nrdot.componentLabels" (dict "Context" . "component" "privileged-helper") | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "nrdot.componentSelectorLabels" (dict "Context" . "component" "privileged-helper") | nindent 4 }}
  ports:
  - name: socket
    port: 8090
    targetPort: socket
    protocol: TCP
  - name: metrics
    port: 8084
    targetPort: metrics
    protocol: TCP
{{- end }}