{{- if .Values.collector.enabled }}
{{- $component := .Values.collector -}}
{{- $componentName := "collector" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nrdot.fullname" . }}-collector
  namespace: {{ include "nrdot.namespace" . }}
  labels:
    {{- include "nrdot.componentLabels" (dict "Context" . "component" $componentName) | nindent 4 }}
spec:
  {{- if not .Values.collector.autoscaling.enabled }}
  replicas: {{ .Values.collector.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "nrdot.componentSelectorLabels" (dict "Context" . "component" $componentName) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nrdot.componentSelectorLabels" (dict "Context" . "component" $componentName) | nindent 8 }}
      annotations:
        {{- include "nrdot.checksumAnnotations" . | nindent 8 }}
        {{- include "nrdot.prometheusAnnotations" (dict "port" "8888") | nindent 8 }}
        {{- with .Values.collector.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "nrdot.imagePullSecrets" (dict "Context" . "component" $component) | nindent 6 }}
      serviceAccountName: {{ include "nrdot.serviceAccountName" (dict "Context" . "component" $componentName) }}
      {{- include "nrdot.podSecurityContext" (dict "Context" . "component" $component) | nindent 6 }}
      initContainers:
      - name: wait-for-config
        image: busybox:1.35
        command: ['sh', '-c', 'until test -f /etc/otel/otelcol-config.yaml; do echo waiting for config; sleep 2; done']
        volumeMounts:
        - name: config
          mountPath: /etc/otel
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
            - ALL
      containers:
      - name: collector
        image: {{ include "nrdot.image" (dict "component" $component "Values" .Values "Chart" .Chart) }}
        imagePullPolicy: {{ .Values.collector.image.pullPolicy }}
        args:
          - --config=/etc/otel/otelcol-config.yaml
          - --feature-gates=telemetry.useOtelForInternalMetrics
        ports:
        - name: otlp-grpc
          containerPort: 4317
          protocol: TCP
        - name: otlp-http
          containerPort: 4318
          protocol: TCP
        - name: metrics
          containerPort: 8888
          protocol: TCP
        - name: health
          containerPort: 13133
          protocol: TCP
        - name: zpages
          containerPort: 55679
          protocol: TCP
        env:
        {{- include "nrdot.newrelicEnvVars" . | nindent 8 }}
        {{- include "nrdot.commonEnvVars" . | nindent 8 }}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name={{ include "nrdot.fullname" . }}-collector,deployment.environment=kubernetes"
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: K8S_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        {{- include "nrdot.extraEnvVars" . | nindent 8 }}
        volumeMounts:
        - name: config
          mountPath: /etc/otel
          readOnly: true
        - name: collector-data
          mountPath: /var/lib/otel
        - name: temp
          mountPath: /tmp
        - name: cache
          mountPath: /var/cache/otel
        {{- with .Values.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.collector.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: health
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: health
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        {{- include "nrdot.securityContext" (dict "component" $component) | nindent 8 }}
      volumes:
      - name: config
        configMap:
          name: {{ include "nrdot.fullname" . }}-config
          items:
          - key: otelcol-config.yaml
            path: otelcol-config.yaml
      - name: collector-data
        emptyDir:
          sizeLimit: 5Gi
      - name: temp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      {{- with .Values.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- include "nrdot.affinity" (dict "Context" . "component" $component "componentName" $componentName) | nindent 6 }}
      {{- include "nrdot.nodeSelector" (dict "Context" . "component" $component) | nindent 6 }}
      {{- include "nrdot.tolerations" (dict "Context" . "component" $component) | nindent 6 }}
      {{- with .Values.collector.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}