apiVersion: v1
kind: Service
metadata:
  name: nrdot-service
  namespace: nrdot-e2e
  labels:
    app: nrdot
spec:
  type: ClusterIP
  selector:
    app: nrdot
    component: daemonset
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: otlp-http
    port: 4318
    targetPort: 4318
    protocol: TCP
  - name: metrics
    port: 8888
    targetPort: 8888
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nrdot-nodeport
  namespace: nrdot-e2e
  labels:
    app: nrdot
spec:
  type: NodePort
  selector:
    app: nrdot
    component: daemonset
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    nodePort: 30317
    protocol: TCP
  - name: metrics
    port: 8888
    targetPort: 8888
    nodePort: 30888
    protocol: TCP