version: '3.8'

services:
  # Vulnerable application with secrets
  vulnerable-app:
    build: ./vulnerable-app
    container_name: vulnerable-app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_PASSWORD=super_secret_password_123
      - API_KEY=sk-1234567890abcdef
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - GITHUB_TOKEN=ghp_1234567890abcdefghijklmnopqrstuvwxyz
      - STRIPE_SECRET_KEY=sk_test_fake_stripe_key_for_testing
      - JWT_SECRET=my-super-secret-jwt-key
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://nrdot:4317
      - OTEL_SERVICE_NAME=vulnerable-app
    depends_on:
      - nrdot
    networks:
      - security-network

  # NRDOT with security processors
  nrdot:
    image: nrdot-host:latest
    container_name: nrdot-security
    volumes:
      - ./configs/nrdot-config.yaml:/etc/nrdot/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NRDOT_CONFIG=/etc/nrdot/config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8888:8888"   # Metrics
      - "13133:13133" # Health check
    networks:
      - security-network

  # Elasticsearch for log storage
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch-security
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - security-network

  # Jaeger for traces
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-security
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14250:14250"
    networks:
      - security-network

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-security
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - security-network

networks:
  security-network:
    driver: bridge